services:
  api:
    build:
      context: ./backend
    container_name: api
    command: uv run fastapi dev api.py --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/renders:/app/renders
    depends_on:
      - redis

  worker:
    container_name: worker
    command: uv run celery -A api.brocolli worker --loglevel=info
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/app
      - ./backend/renders:/app/renders
    depends_on:
      - redis
      - api

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    container_name: frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api

volumes:
  redis_data:
